service: appd-lambda-nodejs

provider:
  name: aws
  runtime: nodejs10.x

  # you can overwrite defaults here
  stage: dev
  region: us-west-2
  environment:
    AWS_REGION_STR: ${opt:region, self:provider.region}
    CANDIDATE_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    CANDIDATE_EMAIL_TABLE: "candidate-email-${opt:stage, self:provider.stage}"
    APPDYNAMICS_ACCOUNT_NAME: "aws-sandbox"
    APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY: "9ayhsaoe096t"
    APPDYNAMICS_APPLICATION_NAME: "WayneLambdaTest"
    APPDYNAMICS_CONTROLLER_HOST: "aws-sandbox.saas.appdynamics.com"
    APPDYNAMICS_SERVERLESS_API_ENDPOINT: "https://pdx-sls-agent-api.saas.appdynamics.com"
    APPDYNAMICS_CONTROLLER_PORT: 443    
    APPDYNAMICS_LOG_LEVEL: "DEBUG"   
    AWS_LAMBDA_EXEC_WRAPPER: "/opt/appdynamics-extension-script" 

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - lambda:InvokeFunction
        - secretsmanager:GetSecretValue
      Resource: "*"

resources:
  Resources:
    CandidatesDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Delete
      Properties:
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.CANDIDATE_TABLE}
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true

functions:
  lambda-1:
    handler: handler.doFunctionAsync
    description: Sample Lambda function in NodeJS for AppD Lambda Instrumentation
    layers:
      - arn:aws:lambda:${opt:region, self:provider.region}:716333212585:layer:appdynamics-lambda-extension:9
    memorySize: 256
    timeout: 30
    environment:
      APPDYNAMICS_TIER_NAME: ${self:service}-lambda-1
    events:
      - http:
          path: /{proxy+}
          method: any    

  lambda-2:
    handler: handler.doFunctionAsync2
    description: Second sample Lambda function
    layers:
      - arn:aws:lambda:${opt:region, self:provider.region}:716333212585:layer:appdynamics-lambda-extension:9
    memorySize: 256
    timeout: 30
    environment:
      APPDYNAMICS_TIER_NAME: ${self:service}-lambda-2
